use primeWARE;

truncate table AgendaContato
truncate table Agendamento
truncate table AgendaPagamento
truncate table AgendaPagamentoAgendasPagamentosProdutoFinalProdutosFinais
truncate table AgendaPagamentoAgendasPagamentosTipoDocParcelamentoTiposDocsP2U5
--truncate table AgendaRotina
truncate table AgenteVenda
truncate table AgenteVendaAgentesVendasUnidadeUnidades
truncate table Animal
truncate table Anotacao
--truncate table AparelhoECF
--truncate table Area
--truncate table Atividade
truncate table AuditarEvento
truncate table AuditarEventoComando
truncate table Auditoria
--truncate table Bairro
truncate table Banco
truncate table CabecalhoMovimentoEstoque
truncate table CabMovEstoqueData
truncate table CabMovEstoqueNumero
truncate table CabMovEstoqueTransportador
truncate table CabMovEstoqueValor
truncate table CabMovEstoqueVeiculo
truncate table CaixaRegistradora
--truncate table CampoClasse
--truncate table CampoConsulta
--truncate table CampoParametroRelatorio
truncate table CCe
--truncate table CEPLogradouro
--truncate table CfgCampoClasse
--truncate table CfgExcecao
--truncate table CfgExcecaoClasse
--truncate table CfgExcecaoExcecoesExcecaoSolucaoSolucoes
--truncate table CfgExcecaoVariavel
--truncate table CfgValorClasse
truncate table Cheque
truncate table ChequeEmitido
truncate table ChequeRecebido
--truncate table Cidade
truncate table Classe
truncate table ClasseIndiceTributario
truncate table Cliente
truncate table ClienteClientesAgenteVendaAgentesVenda
truncate table ClienteClientesUnidadeUnidades
--truncate table CodigoANP
--truncate table ColunaParamTipoMovEstoque
--truncate table ComandoClasse
--truncate table ComandoTipoMovEstoque
truncate table Comodo
--truncate table ConfiguracaoFeriado
truncate table Conjuge
--truncate table Consulta
truncate table ContaBancaria
--truncate table ContaCaixa
truncate table ContaCaixaParcMovEstoque
--truncate table ContaCaixaPersMovEstoque
--truncate table ContaCaixaProdutoMovimentoEstoque
truncate table Contato
truncate table Contrato
truncate table Cor
truncate table CorGrade
truncate table Correspondencia
truncate table DataAgendada
truncate table Divisao
--truncate table ECO_ORMAPPING
--truncate table ECO_TABLES
--truncate table ECO_TYPE
truncate table Endereco
truncate table EspecieAnimal
--truncate table Excecao
--truncate table ExcecaoClasse
--truncate table ExcecaoSolucao
--truncate table Feriado
--truncate table FeriadoLocal
--truncate table FeriadoNacional
--truncate table FormaParcelamento
--truncate table FormaParcelamentoFormasParcelamentosTipoDocParcelamentoTiposPIFN
--truncate table FormaParcPoliticaDesconto
truncate table Fornecedor
--truncate table Funcao
truncate table Genero
truncate table GradeCor
truncate table GradeTamanho
truncate table Grupo
--truncate table GrupoExcecao
--truncate table GrupoNCM
--truncate table GrupoTipoDocParc
--truncate table GrupoTipoMovEstoque
truncate table HistoricoMovimentoCaixa
truncate table IndiceFinanceiro
--truncate table Iniciar
truncate table ItemAuditado
truncate table ItemContratado
truncate table ItemContratadoItensItemContratadoProdutoFinalProdutosFinaisItQ4F
truncate table ItemKit
truncate table ItemMovEstoqueFiscal
truncate table ItemMovEstoquePendencia
truncate table ItemMovEstoqueProcessado
truncate table ItemMovEstoqueValor
truncate table ItemMovimentoEstoque
truncate table LocalTrabalho
truncate table LoteProduto
truncate table Marca
truncate table Material
--truncate table Menu
truncate table Modelagem
truncate table MotivoIda
truncate table MovFinHeaderNumero
truncate table MovimentoCaixa
truncate table MovimentoCaixaRegistradora
truncate table MovimentoEstoqueExcecao
truncate table MovimentoFinanceiro
truncate table MovimentoFinanceiroExcecao
truncate table MovimentoFinanceiroHeader
truncate table MovimentoFinanceiroValor
--truncate table NumeroSequencial
update NumeroSequencial set UltimoNumero = -1
--truncate table NumeroSequencialNumerosSequenciaisTipoMovEstoqueNumeradorTipoK1F
truncate table ObjetoAuditado
--truncate table ObjetoCampoClasse
--truncate table ObjetoValorClasse
truncate table ObsCabMovEstoque
truncate table Ocupacao
truncate table OperacaoCaixaRegistradora
--truncate table ParametroRelatorio
--truncate table ParametroRelatorioValidade
--truncate table ParametroSistema
--truncate table ParametroSistemaNumerador
--truncate table ParametroTipoMovEstoque
truncate table Parceiro
truncate table ParcelaMovimentoEstoque
truncate table Parceria
truncate table ParcMovEstoqueValor
--truncate table Perfil
--truncate table PerfilPerfisPesquisaPesquisas
--truncate table Permissao
--truncate table PermissaoPermissoesFuncaoFuncoes
delete from Personalidade where Login <> 'Admin'
--truncate table PersonalidadeCfgExcecao
--truncate table PersonalidadeCfgExcecaoVariavel
--truncate table PersonalidadeExcecao
--truncate table Pesquisa
--truncate table PesquisaCampo
--truncate table PesquisaColuna
truncate table PessoaFisica
truncate table PessoaJuridica
truncate table PessoaJuridicaEmpresasPersonalidadeSocios
truncate table Preco
--truncate table PreComandoClasse
truncate table Produto
--truncate table ProdutoCfgExcecao
--truncate table ProdutoCfgExcecaoVariavel
--truncate table ProdutoEquivalente
--truncate table ProdutoExcecao
truncate table ProdutoFinal
truncate table ProdutoLocacao
truncate table ProdutoProdutosFornecedorFornecedores
truncate table Quarto
truncate table RacaAnimal
truncate table ReferenciaComercial
truncate table ReferenciaPessoal
truncate table Regiao
--truncate table Relatorio
truncate table Rota
--truncate table Rotina
--truncate table RotinaComando
--truncate table RotinaParametro
--truncate table RotinaParametroCampo
--truncate table RotinaPreComando
--truncate table RotinaValidacao
truncate table SaldoContaCaixa
truncate table SaldoProduto
--truncate table ServidorSMTP
truncate table SexoAplicavel
truncate table StatusCorrespondencia
truncate table TabelaPreco
truncate table TabelaPrecoUnidade
truncate table TalaoCheque
truncate table Tamanho
truncate table TamanhoGrade
--truncate table Tela
--truncate table TelaItem
truncate table Telefone
--truncate table TipoAnotacao
--truncate table TipoCampoData
--truncate table TipoCliente
--truncate table TipoContrato
--truncate table TipoDocParcECF
--truncate table TipoDocParcelamento
--truncate table TipoDocParcelamentoTiposParcelamentosTipoMovimentoEstoqueTipoYSF
--truncate table TipoDocParcelamentoTiposParcelamentosUnidadeUnidades
--truncate table TipoDocParcPoliticaDesconto
--truncate table TipoEndereco
--truncate table TipoFone
--truncate table TipoIndiceFinanceiro
--truncate table TipoMovEstoqueAgendaContato
--truncate table TipoMovEstoqueAgendaContatoProduto
--truncate table TipoMovEstoqueEmissao
--truncate table TipoMovEstoqueExcecao
--truncate table TipoMovEstoqueNumerador
--truncate table TipoMovEstoqueValor
--truncate table TipoMovEstoqueVariavel
--truncate table TipoMovFinEmissao
--truncate table TipoMovFinExcecao
--truncate table TipoMovFinNumerador
--truncate table TipoMovFinValor
--truncate table TipoMovimentoEstoque
--truncate table TipoMovimentoEstoqueTiposMovimentoEstoqueSintegraUnidadeUnidaT6B
--truncate table TipoMovimentoEstoqueTiposMovimentosEstoqueUnidadeUnidades
--truncate table TipoMovimentoFinanceiro
--truncate table TipoMovimentoFinanceiroTiposMovimentoFinanceiroUnidadeUnidades
--truncate table TipoObservacao
--truncate table TipoTributacao
truncate table TituloFinanceiro
--truncate table Tributo
--truncate table TributoGrupoNCM
--truncate table Unidade
--truncate table UnidadeUnidadesFormaParcelamentoFormasParcelamento
truncate table Vacina
truncate table VacinaAplicada
truncate table Vacinante
truncate table VacinaPrevista
--truncate table ValorClasse
truncate table Veiculo
truncate table VeiculoAno
truncate table VeiculoCapacidade
truncate table VeiculoCategoria
truncate table VeiculoCombustivel
truncate table VeiculoCor
truncate table VeiculoEspecie
truncate table VeiculoMarca
truncate table VeiculoModelo
truncate table VeiculoPotencia
truncate table VeiculoTipo