USE [iLabor]
GO

/****** Object:  UserDefinedFunction [dbo].[RetiraraCaracteresEspeciais]    Script Date: 11/13/2018 18:40:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE FUNCTION [dbo].[RetiraraCaracteresEspeciais]
(
    @TEXTO VARCHAR(MAX)
)
RETURNS VARCHAR(MAX)
AS
BEGIN
 
    DECLARE @TEXTO_FORMATADO VARCHAR(MAX)
    SET @TEXTO_FORMATADO = UPPER(@TEXTO)

 IF @TEXTO_FORMATADO IS NULL BEGIN 
     RETURN NULL
 END
 
	SET @TEXTO_FORMATADO = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@TEXTO_FORMATADO,'á','a'),'à','a'),'â','a'),'ã','a'),'ä','a')
    SET @TEXTO_FORMATADO = REPLACE(REPLACE(REPLACE(REPLACE(@TEXTO_FORMATADO,'é','e'),'è','e'),'ê','e'),'ë','e')
    SET @TEXTO_FORMATADO = REPLACE(REPLACE(REPLACE(REPLACE(@TEXTO_FORMATADO,'í','i'),'ì','i'),'î','i'),'ï','i')
    SET @TEXTO_FORMATADO = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@TEXTO_FORMATADO,'ó','o'),'ò','o'),'ô','o'),'õ','o'),'ö','o')
    SET @TEXTO_FORMATADO = REPLACE(REPLACE(REPLACE(REPLACE(@TEXTO_FORMATADO,'ú','u'),'ù','u'),'û','u'),'ü','u')
    SET @TEXTO_FORMATADO = REPLACE(@TEXTO_FORMATADO,'ý','y')
    SET @TEXTO_FORMATADO = REPLACE(@TEXTO_FORMATADO,'ñ','n')
    SET @TEXTO_FORMATADO = REPLACE(@TEXTO_FORMATADO,'ç','c')
 
        
--    SET @TEXTO_FORMATADO = @TEXTO_FORMATADO
 
    RETURN upper(@TEXTO_FORMATADO)
 
END

GO


